spring:
  application:
    name: lu-alves-decor-catalog
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://127.0.0.1:5432/decor_manager}
    username: ${SPRING_R2DBC_USERNAME:user}
    password: ${SPRING_R2DBC_PASSWORD:password}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/decor-manager-catalog}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus